"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { GraduationCap } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/input";
import { Panel } from "@/components/ui/panel";

type CatalogClass={id:string;name:string;code:string;academicYear:string;courses:{id:string;title:string;code:string|null}[]};

export default function SignupPage(){
  const [classes,setClasses]=useState<CatalogClass[]>([]);const [name,setName]=useState("");const [email,setEmail]=useState("");const [classId,setClassId]=useState("");const [courseIds,setCourseIds]=useState<string[]>([]);const [status,setStatus]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch(`${API_BASE_URL}/api/admissions/catalog`).then(r=>r.json()).then(setClasses).catch(()=>setStatus("Admission catalog could not be loaded."));},[]);
  const selectedClass=useMemo(()=>classes.find(item=>item.id===classId),[classes,classId]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setStatus(null);try{const response=await fetch(`${API_BASE_URL}/api/admissions/request`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,desiredClassId:classId,selectedCourseIds:courseIds})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(Array.isArray(data?.message)?data.message.join(", "):data?.message||"Request failed");setName("");setEmail("");setClassId("");setCourseIds([]);setStatus("Admission request submitted. You will receive an email after admin review.");}catch(error){setStatus(error instanceof Error?error.message:"Admission request failed.");}finally{setBusy(false);}}
  function toggleCourse(id:string){setCourseIds(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);}
  return <main className="grid min-h-screen bg-ink-950 lg:grid-cols-[0.8fr_1.2fr]">
    <section className="hidden bg-[radial-gradient(circle_at_30%_20%,rgba(124,58,237,.22),transparent_35%),#0B1020] p-14 lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 text-white"><GraduationCap className="text-accent-cyan"/><span className="font-bold">SmartAcademy</span></div><div><p className="text-xs uppercase tracking-[.35em] text-accent-cyan">Student admissions</p><h1 className="mt-5 text-5xl font-semibold leading-tight text-white">Begin your learning journey.</h1><p className="mt-5 max-w-md leading-7 text-slate-400">Choose your class and courses. Our admissions team will review availability and guide you through registration.</p></div><p className="text-xs text-slate-600">Admission does not create portal access until final approval.</p></section>
    <section className="flex items-center justify-center px-6 py-12"><Panel className="w-full max-w-2xl" glass={false}><p className="text-xs font-bold uppercase tracking-[.3em] text-accent-purple">Admission Request</p><h2 className="mt-3 text-3xl font-semibold text-white">Apply as a student</h2><p className="mt-2 text-sm text-slate-400">Tell us which class and courses you want to join.</p><form onSubmit={submit} className="mt-8 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Input required placeholder="Student full name" value={name} onChange={e=>setName(e.target.value)}/><Input required type="email" placeholder="Student email" value={email} onChange={e=>setEmail(e.target.value)}/></div><Select required value={classId} onChange={e=>{setClassId(e.target.value);setCourseIds([]);}}><option value="">Select class</option>{classes.map(item=><option key={item.id} value={item.id}>{item.name} ({item.code}) · {item.academicYear}</option>)}</Select>{selectedClass&&<div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-slate-500">Select Courses</p><div className="grid gap-3 sm:grid-cols-2">{selectedClass.courses.map(course=><label key={course.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 transition ${courseIds.includes(course.id)?"border-accent-cyan/50 bg-accent-cyan/10":"border-white/10 bg-white/[.03]"}`}><input type="checkbox" checked={courseIds.includes(course.id)} onChange={()=>toggleCourse(course.id)} className="accent-cyan-400"/><span className="text-sm text-slate-200">{course.title}</span></label>)}</div>{!selectedClass.courses.length&&<Alert variant="neutral">No courses are currently offered in this class.</Alert>}</div>}<Button fullWidth type="submit" disabled={busy||!courseIds.length}>{busy?"Submitting...":"Request Admission"}</Button></form>{status&&<Alert variant="info" className="mt-5">{status}</Alert>}<p className="mt-6 text-center text-sm text-slate-500">Already approved? <Link href="/login" className="text-accent-cyan">Sign in</Link></p></Panel></section>
  </main>;
}
