"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { GraduationCap, Upload } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input, Select, Textarea } from "@/components/ui/input";

type Invitation={name:string;email:string;className:string;sectionName:string;status:string};
const initial={phoneNumber:"",password:"",confirmPassword:"",dateOfBirth:"",gender:"",cnicBForm:"",nationality:"Pakistani",address:"",city:"",previousSchool:"",lastGrade:"",guardianName:"",guardianRelation:"",guardianPhone:"",guardianEmail:"",guardianOccupation:"",medicalNotes:""};

export default function StudentRegistrationPage(){const params=useParams<{token:string}>();const token=decodeURIComponent(params.token);const [invitation,setInvitation]=useState<Invitation|null>(null);const [form,setForm]=useState(initial);const [files,setFiles]=useState<Record<string,File[]>>({});const [message,setMessage]=useState<string|null>(null);const [busy,setBusy]=useState(false);
useEffect(()=>{fetch(`${API_BASE_URL}/api/admissions/register/${encodeURIComponent(token)}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.message);setInvitation(data);}).catch(e=>setMessage(e.message||"Invalid registration link"));},[token]);
function update(key:keyof typeof initial,value:string){setForm(current=>({...current,[key]:value}));}function choose(field:string,list:FileList|null){setFiles(current=>({...current,[field]:list?Array.from(list):[]}));}
async function submit(event:FormEvent){event.preventDefault();if(form.password!==form.confirmPassword)return setMessage("Passwords do not match.");for(const field of ["profilePhoto","birthCertificate","guardianCnic","previousResult"])if(!files[field]?.length)return setMessage(`Please upload ${field.replace(/([A-Z])/g," $1").toLowerCase()}.`);setBusy(true);setMessage(null);try{const data=new FormData();Object.entries(files).forEach(([field,list])=>list.forEach(file=>data.append(field,file)));const upload=await fetch(`${API_BASE_URL}/api/admissions/documents`,{method:"POST",body:data});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.message||"Document upload failed");const response=await fetch(`${API_BASE_URL}/api/admissions/complete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:form.password,phoneNumber:form.phoneNumber,personalDetails:{dateOfBirth:form.dateOfBirth,gender:form.gender,cnicBForm:form.cnicBForm,nationality:form.nationality,address:form.address,city:form.city,medicalNotes:form.medicalNotes},guardianDetails:{name:form.guardianName,relation:form.guardianRelation,phone:form.guardianPhone,email:form.guardianEmail,occupation:form.guardianOccupation},educationDetails:{previousSchool:form.previousSchool,lastGrade:form.lastGrade},documentLinks:uploaded.files})});const result=await response.json();if(!response.ok)throw new Error(result.message||"Registration failed");setMessage("Registration submitted successfully. You can sign in after admin approval.");}catch(error){setMessage(error instanceof Error?error.message:"Registration failed");}finally{setBusy(false);}}
if(!invitation)return <main className="flex min-h-screen items-center justify-center bg-ink-950 p-6"><Alert variant="neutral">{message||"Loading registration..."}</Alert></main>;
return <main className="min-h-screen bg-ink-950 px-5 py-10 text-slate-100"><div className="mx-auto max-w-5xl"><header className="rounded-3xl border border-white/10 bg-gradient-to-r from-accent-purple/15 to-accent-cyan/10 p-7"><div className="flex items-center gap-3"><GraduationCap className="text-accent-cyan"/><span className="font-bold">SmartAcademy</span></div><h1 className="mt-6 text-4xl font-bold">Complete your admission form</h1><p className="mt-2 text-slate-400">{invitation.name} · {invitation.className}, Section {invitation.sectionName}</p></header><form onSubmit={submit} className="mt-6 space-y-6">
<Section title="Account Access"><Grid><Field label="Phone"><Input required value={form.phoneNumber} onChange={e=>update("phoneNumber",e.target.value)}/></Field><Field label="Password"><Input required type="password" minLength={6} value={form.password} onChange={e=>update("password",e.target.value)}/></Field><Field label="Confirm Password"><Input required type="password" value={form.confirmPassword} onChange={e=>update("confirmPassword",e.target.value)}/></Field></Grid></Section>
<Section title="Personal Details"><Grid><Field label="Date of Birth"><Input required type="date" value={form.dateOfBirth} onChange={e=>update("dateOfBirth",e.target.value)}/></Field><Field label="Gender"><Select required value={form.gender} onChange={e=>update("gender",e.target.value)}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></Select></Field><Field label="CNIC / B-Form"><Input required value={form.cnicBForm} onChange={e=>update("cnicBForm",e.target.value)}/></Field><Field label="Nationality"><Input required value={form.nationality} onChange={e=>update("nationality",e.target.value)}/></Field><Field label="City"><Input required value={form.city} onChange={e=>update("city",e.target.value)}/></Field><Field label="Address"><Input required value={form.address} onChange={e=>update("address",e.target.value)}/></Field></Grid><Field label="Medical Notes"><Textarea value={form.medicalNotes} onChange={e=>update("medicalNotes",e.target.value)} placeholder="Allergies or health information (optional)"/></Field></Section>
<Section title="Guardian Details"><Grid><Field label="Guardian Name"><Input required value={form.guardianName} onChange={e=>update("guardianName",e.target.value)}/></Field><Field label="Relationship"><Input required value={form.guardianRelation} onChange={e=>update("guardianRelation",e.target.value)}/></Field><Field label="Phone"><Input required value={form.guardianPhone} onChange={e=>update("guardianPhone",e.target.value)}/></Field><Field label="Email"><Input type="email" value={form.guardianEmail} onChange={e=>update("guardianEmail",e.target.value)}/></Field><Field label="Occupation"><Input value={form.guardianOccupation} onChange={e=>update("guardianOccupation",e.target.value)}/></Field></Grid></Section>
<Section title="Previous Education"><Grid><Field label="Previous School"><Input required value={form.previousSchool} onChange={e=>update("previousSchool",e.target.value)}/></Field><Field label="Last Grade Completed"><Input required value={form.lastGrade} onChange={e=>update("lastGrade",e.target.value)}/></Field></Grid></Section>
<Section title="Documents"><div className="grid gap-4 sm:grid-cols-2">{[["profilePhoto","Profile Photo",false],["birthCertificate","Birth Certificate / B-Form",false],["studentCnic","Student CNIC (if available)",true],["guardianCnic","Guardian CNIC (front/back)",true],["previousResult","Previous Result Cards",true],["otherDocuments","Other Documents",true]].map(([field,label,multiple])=><label key={String(field)} className="rounded-xl border border-dashed border-white/15 bg-white/[.03] p-4"><span className="flex items-center gap-2 font-semibold"><Upload size={16} className="text-accent-cyan"/>{label}</span><input className="mt-3 block w-full text-xs text-slate-400" type="file" multiple={Boolean(multiple)} onChange={e=>choose(String(field),e.target.files)}/><span className="mt-2 block text-xs text-slate-600">{files[String(field)]?.map(file=>file.name).join(", ")||"No file selected"}</span></label>)}</div></Section>
{message&&<Alert variant="info">{message}</Alert>}<Button type="submit" fullWidth disabled={busy}>{busy?"Uploading and submitting...":"Submit Admission Form"}</Button></form></div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="mb-5 text-xl font-bold text-white">{title}</h2><div className="space-y-4">{children}</div></section>}function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</div>}function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500">{label}</span>{children}</label>}
